stylesheets:
  vendor:
    - public/vendor/*/*.css
  
  compiled:
    - public/stylesheets/compiled/*.css

javascripts:
  vendor:
    - public/vendor/*/*.js
  
  compiled:
    - public/javascripts/compiled/*.js